Fixup build on qt6
sailfishos/nemo-qml-plugin-devicelock pull request #6
Opened 2023-07-24 20:49 UTC by neochapay

2023-08-09 17:24 UTC, attah commented on src/daemon/daemon.pro
> +        c++17 \
At least when i make apps for SFOS, their Qt version does not recognize c++17 as CONFIG, so i had to resort to `QMAKE_CXXFLAGS += -std=c++17`.
(And c++11 maps to `-std=gnu++0x`)

2023-08-09 18:27 UTC, mlehtima commented on src/plugin/plugin.cpp
> +//        qmlRegisterType<NemoDeviceLock::FingerprintModel>();
Is this intentionally disabled and will this cause issues?

2023-11-28 08:01 UTC, pvuorela requested changes
Commenting out the finger print model doesn't look proper and the review comment unaddressed. Marking as needing changes.

2025-06-20 08:30 UTC, jmlich commented
@pvuorela is current version ok?

2026-05-14 12:11 UTC, PureTryOut commented
@pvuorela could you re-review this?

2026-05-14 12:34 UTC, pvuorela commented on src/plugin/plugin.cpp
> +#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
qmlRegisterAnonymousType is introduced in 5.14

2026-05-25 06:54 UTC, pvuorela approved these changes

2026-05-25 06:55 UTC, merged